services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - API_URL=http://host.docker.internal:8002 # Tambahkan variabel lingkungan di sini
