services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - 'auth:/app/.wwebjs_auth'
      - 'cache:/app/.wwebjs_cache'
      - 'node_modules:/app/node_modules'
    env_file: ".env"
volumes:
  auth:
    driver: local
  cache:
    driver: local
  node_modules:
    driver: local